Repository oppia/oppia-android, pull requests merged in 2021-08, with the labels that each got.

#3612 Fix #3578: Deleted toolbar.xml (land)
  app/src/main/res/layout-land/toolbar.xml
Labels: PR don't merge - NEEDS UPDATE

#3267 Fix #3266: [RTL] High-fi Image from rich text is center aligned in Exploration Player.
  app/src/sharedTest/java/org/oppia/android/app/parser/HtmlParserTest.kt
  utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt
Labels: Type: Task

#3181 Fix #3134: Admin Settings shows error message for null pin entries.
  app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/profile/AdminSettingsDialogFragmentPresenter.kt
  app/src/main/res/values/strings.xml
  app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt
  app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt
Labels: PR don't merge - NEEDS UPDATE

#3644 Fix #3583: Merge topic_practice_footer_view into single layout file.
  app/src/main/res/layout-land/topic_practice_footer_view.xml
  app/src/main/res/layout-sw600dp-land/topic_practice_footer_view.xml
  app/src/main/res/layout-sw600dp-port/topic_practice_footer_view.xml
  app/src/main/res/layout/topic_practice_footer_view.xml
  app/src/main/res/values-sw600dp-land/dimens.xml
  app/src/main/res/values-sw600dp-port/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: PR: LGTM

#3593 Fix #3592: [RTL] High-fi Add support for RTL in audio player and other drawables included in Oppia
  app/src/main/res/drawable/ic_profile_exit.xml
  app/src/main/res/drawable/ic_upload_photo.xml
  app/src/main/res/drawable/icon_search_white_24dp.xml
Labels: PR: LGTM

#3452 [RunAllTests] Fix #3451: [RTL] High-fi Add support for RTL in binding adapters
  app/BUILD.bazel
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/oppia/android/app/activity/ActivityComponent.kt
  app/src/main/java/org/oppia/android/app/databinding/MarginBindingAdapters.java
  app/src/main/java/org/oppia/android/app/databinding/StateAssemblerMarginBindingAdapters.java
  app/src/main/java/org/oppia/android/app/databinding/StateAssemblerPaddingBindingAdapters.java
  app/src/main/java/org/oppia/android/app/testing/MarginBindingAdaptersTestActivity.kt
  app/src/main/java/org/oppia/android/app/testing/StateAssemblerMarginBindingAdaptersTestActivity.kt
  app/src/main/java/org/oppia/android/app/testing/StateAssemblerPaddingBindingAdaptersTestActivity.kt
  app/src/main/res/layout/test_margin_bindable_adapter_activity.xml
  app/src/sharedTest/java/org/oppia/android/app/databinding/MarginBindingAdaptersTest.kt
  app/src/sharedTest/java/org/oppia/android/app/databinding/StateAssemblerMarginBindingAdaptersTest.kt
  app/src/sharedTest/java/org/oppia/android/app/databinding/StateAssemblerPaddingBindingAdaptersTest.kt
  scripts/assets/accessibility_label_exemptions.textproto
  scripts/assets/test_file_exemptions.textproto
Labels: Type: Task

#3652 Fix #3651: [RTL] High-fi rotation animation for icon in Topic lesson and Hints and Solution
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/oppia/android/app/activity/ActivityComponent.kt
  app/src/main/java/org/oppia/android/app/databinding/ViewBindingAdapters.java
  app/src/main/java/org/oppia/android/app/testing/ViewBindingAdaptersTestActivity.kt
  app/src/main/res/layout/activity_view_binding_adapters_test.xml
  app/src/sharedTest/java/org/oppia/android/app/databinding/ViewBindingAdaptersTest.kt
  scripts/assets/accessibility_label_exemptions.textproto
  scripts/assets/test_file_exemptions.textproto
Labels: Type: Task

#3466 Fix #3406: [RTL] High-fi Recently- Played Activity List
  app/BUILD.bazel
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingListAdapter.kt
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingStoryViewModel.kt
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedFragmentPresenter.kt
  app/src/main/res/layout-land/ongoing_story_card.xml
  app/src/main/res/layout-sw600dp-land/ongoing_story_card.xml
  app/src/main/res/layout-sw600dp-port/ongoing_story_card.xml
  app/src/main/res/layout/ongoing_story_card.xml
  app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt
Labels: Type: Task, PR: LGTM

#3594 Setup Oppiabot stale checks for Oppia Android
  .github/CODEOWNERS
  .github/stale.yml
Labels: PR don't merge - NEEDS UPDATE

#3632 Fix #3498: Add CI check to ensure license text is never checked into Git
  .github/CODEOWNERS
  .github/workflows/static_checks.yml
  app/src/main/res/values/third_party_dependencies.xml
  scripts/BUILD.bazel
  scripts/src/java/org/oppia/android/scripts/license/BUILD.bazel
  scripts/src/java/org/oppia/android/scripts/license/LicenseTextsCheck.kt
  scripts/src/javatests/org/oppia/android/scripts/license/BUILD.bazel
  scripts/src/javatests/org/oppia/android/scripts/license/LicenseTextsCheckTest.kt
Labels: PR: LGTM

#3597 Fix #3532: Deleted help_activity.xml (land) file
  app/src/main/res/layout-land/help_activity.xml
  app/src/main/res/layout/help_activity.xml
  app/src/main/res/values/dimens.xml
Labels: PR don't merge - NEEDS UPDATE, PR: LGTM

#3688 Fixes #3673: Concept card bottom padding
  app/src/main/res/layout/concept_card_fragment.xml
Labels: PR: LGTM

#3699 Restrict code ownership for strings
  .github/CODEOWNERS
Labels: PR: LGTM

#3667 Fix #3656: [RTL] High-fi Add support for RTL in Story Activity
  app/src/main/res/layout-land/story_chapter_view.xml
  app/src/main/res/layout-sw600dp/story_chapter_view.xml
  app/src/main/res/layout/story_chapter_view.xml
  app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt
Labels: Type: Task, PR: LGTM

#3707 Exclude instrumentation tests from generic build patterns
  instrumentation/oppia_instrumentation_test.bzl
Labels: PR: LGTM

#3675 Fix #3674: Added new test cases in PlatformParameterIntegrationTest
  app/BUILD.bazel
  app/build.gradle
  app/src/main/java/org/oppia/android/app/testing/SplashTestActivityPresenter.kt
  app/src/test/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt
  scripts/assets/kdoc_validity_exemptions.textproto
  testing/src/main/java/org/oppia/android/testing/network/BUILD.bazel
  testing/src/main/java/org/oppia/android/testing/network/MockPlatformParameterService.kt
  utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterConstants.kt
Labels: PR: LGTM

#3716 Fix #2032 & #3714: stabilize AndroidX workers
  domain/build.gradle
  domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader/LogUploadWorker.kt
  domain/src/main/java/org/oppia/android/domain/platformparameter/syncup/PlatformParameterSyncUpWorker.kt
  scripts/assets/file_content_validation_checks.textproto
  scripts/src/java/org/oppia/android/scripts/regex/RegexPatternValidationCheck.kt
  scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt
Labels: PR: LGTM

#3727 Add checks to force RTL layout attributes.
  scripts/assets/file_content_validation_checks.textproto
  scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt
Labels: PR: LGTM

#3702 Fix #3108: Applied dimens value navigation_drawer_width to layout_width
  app/src/main/res/layout-land/administrator_controls_activity.xml
  app/src/main/res/layout-land/home_activity.xml
  app/src/main/res/layout-land/option_activity.xml
  app/src/main/res/layout-sw600dp-port/home_activity.xml
  app/src/main/res/layout-sw600dp/administrator_controls_activity.xml
  app/src/main/res/layout-sw600dp/help_activity.xml
  app/src/main/res/layout-sw600dp/option_activity.xml
  app/src/main/res/layout/administrator_controls_activity.xml
  app/src/main/res/layout/developer_options_activity.xml
  app/src/main/res/layout/home_activity.xml
  app/src/main/res/layout/option_activity.xml
Labels: PR: LGTM
