Repository oppia/oppia-android, pull requests merged in 2021-07, with the labels that each got.

#3391 Fix #1643: Highfi image region selection
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ImageRegionSelectionInteractionViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/InteractionViewModelModule.kt
  app/src/main/res/layout/image_region_selection_interaction_item.xml
Labels: PR: LGTM

#3373 Fix #3365: [RTL] High-fi All general buttons
  app/src/main/res/layout/replay_button_item.xml
  app/src/main/res/layout/return_to_topic_button_item.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-sw600dp-land/dimens.xml
  app/src/main/res/values-sw600dp-port/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: Type: Task

#3355 Fix #3354:[RTL] High-fi Interaction View
  app/src/main/res/layout/fraction_interaction_item.xml
  app/src/main/res/layout/numeric_input_interaction_item.xml
  app/src/main/res/layout/ratio_input_interaction_item.xml
  app/src/main/res/layout/text_input_interaction_item.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-sw600dp-land/dimens.xml
  app/src/main/res/values-sw600dp-port/dimens.xml
Labels: PR: LGTM

#3412 Fixes #3130: Merged Switch click with TextViews in AdministratorControlsActivity
  app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt
  app/src/main/res/layout-land/administrator_controls_download_permissions_view.xml
  app/src/main/res/layout-sw600dp/administrator_controls_download_permissions_view.xml
  app/src/main/res/layout/administrator_controls_download_permissions_view.xml
  app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt
Labels: PR: LGTM

#3323 Fix #3322: Platform parameter singleton and Generic Interface
  domain/BUILD.bazel
  domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterSingletonImpl.kt
  domain/src/test/java/org/oppia/android/domain/platformparameter/PlatformParameterSingletonTest.kt
  utility/BUILD.bazel
  utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterSingleton.kt
  utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterValue.kt
Labels: PR: LGTM

#3339 Fix #3297: Implement Force Crash App Feature
  app/BUILD.bazel
  app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsActivity.kt
  app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsViewModel.kt
  app/src/main/java/org/oppia/android/app/devoptions/ForceCrashButtonClickListener.kt
  app/src/main/java/org/oppia/android/app/devoptions/devoptionsitemviewmodel/DeveloperOptionsOverrideAppBehaviorsViewModel.kt
  app/src/main/res/layout/developer_options_override_app_behaviors_view.xml
  app/src/sharedTest/java/org/oppia/android/app/devoptions/DeveloperOptionsActivityTest.kt
Labels: PR: LGTM

#3361 Fix #3360: Platform Parameter Dagger Module and Constants File [BLOCKED on #3323]
  app/src/main/java/org/oppia/android/app/application/ApplicationComponent.kt
  domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterModule.kt
  domain/src/test/java/org/oppia/android/domain/platformparameter/PlatformParameterModuleTest.kt
  domain/src/test/java/org/oppia/android/domain/platformparameter/PlatformParameterSingletonTest.kt
  testing/src/main/java/org/oppia/android/testing/platformparameter/TestPlatformParameterModule.kt
  utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterConstants.kt
  utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterValue.kt
Labels: PR: LGTM

#3430 Fix #3386: Introduce a PlatformParameterController
  domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterController.kt
  domain/src/test/java/org/oppia/android/domain/platformparameter/PlatformParameterControllerTest.kt
Labels: PR: LGTM

#3376 Fix #3302 and #3307: Implement View Event Logs Feature
  app/BUILD.bazel
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/oppia/android/app/activity/ActivityComponent.kt
  app/src/main/java/org/oppia/android/app/application/ApplicationComponent.kt
  app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsActivity.kt
  app/src/main/java/org/oppia/android/app/devoptions/DeveloperOptionsViewModel.kt
  app/src/main/java/org/oppia/android/app/devoptions/RouteToViewEventLogsListener.kt
  app/src/main/java/org/oppia/android/app/devoptions/devoptionsitemviewmodel/DeveloperOptionsViewLogsViewModel.kt
  app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/EventLogItemViewModel.kt
  app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsActivity.kt
  app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsFragment.kt
  app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/devoptions/vieweventlogs/ViewEventLogsViewModel.kt
  app/src/main/java/org/oppia/android/app/fragment/FragmentComponent.kt
  app/src/main/res/drawable/rounded_rect_large_border_radius.xml
  app/src/main/res/layout/developer_options_view_logs_view.xml
  app/src/main/res/layout/view_event_logs_activity.xml
  app/src/main/res/layout/view_event_logs_event_log_item_view.xml
  app/src/main/res/layout/view_event_logs_fragment.xml
  app/src/main/res/values/strings.xml
  app/src/sharedTest/java/org/oppia/android/app/devoptions/DeveloperOptionsActivityTest.kt
  app/src/sharedTest/java/org/oppia/android/app/devoptions/ViewEventLogsActivityTest.kt
  utility/src/main/java/org/oppia/android/util/logging/firebase/BUILD.bazel
  utility/src/main/java/org/oppia/android/util/logging/firebase/DebugEventLogger.kt
  utility/src/main/java/org/oppia/android/util/logging/firebase/DebugLogReportingModule.kt
  utility/src/main/java/org/oppia/android/util/system/OppiaDateTimeFormatter.kt
Labels: PR: LGTM

#3443 Fix #3424 Merge concept_card_fragment into single xml file
  app/src/main/res/layout-land/concept_card_fragment.xml
  app/src/main/res/layout-sw600dp-land/concept_card_fragment.xml
  app/src/main/res/layout-sw600dp-port/concept_card_fragment.xml
  app/src/main/res/layout/concept_card_fragment.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-sw600dp-land/dimens.xml
  app/src/main/res/values-sw600dp-port/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: PR: LGTM

#3433 Fix #3432: [A11y] Content description for rich text based images
  utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt
  utility/src/main/java/org/oppia/android/util/parser/html/ImageTagHandler.kt
  utility/src/test/java/org/oppia/android/util/parser/html/ImageTagHandlerTest.kt
Labels: PR: LGTM

#3402 Fix #3327: Create app layer mechanism for saving checkpoints.
  app/src/main/java/org/oppia/android/app/home/RouteToExplorationListener.kt
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedActivity.kt
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivity.kt
  app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/player/state/testing/StateFragmentTestActivity.kt
  app/src/main/java/org/oppia/android/app/player/state/testing/StateFragmentTestActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/player/stopplaying/ProgressDatabaseFullDialogFragment.kt
  app/src/main/java/org/oppia/android/app/player/stopplaying/StopExplorationDialogFragment.kt
  app/src/main/java/org/oppia/android/app/player/stopplaying/StopStatePlayingSessionWithSavedProgressListener.kt
  app/src/main/java/org/oppia/android/app/player/stopplaying/UnsavedExplorationDialogFragment.kt
  app/src/main/java/org/oppia/android/app/story/StoryActivity.kt
  app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/testing/ExplorationTestActivity.kt
  app/src/main/java/org/oppia/android/app/testing/ExplorationTestActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/testing/TopicTestActivity.kt
  app/src/main/java/org/oppia/android/app/testing/TopicTestActivityForStory.kt
  app/src/main/java/org/oppia/android/app/topic/TopicActivity.kt
  app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivity.kt
  app/src/main/res/values/strings.xml
  app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
  app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt
  app/src/test/java/org/oppia/android/app/player/exploration/ExplorationActivityLocalTest.kt
  app/src/test/java/org/oppia/android/app/player/state/StateFragmentLocalTest.kt
  app/src/test/java/org/oppia/android/app/testing/player/state/StateFragmentAccessibilityTest.kt
  domain/src/main/java/org/oppia/android/domain/exploration/ExplorationDataController.kt
  domain/src/test/java/org/oppia/android/domain/exploration/ExplorationDataControllerTest.kt
  domain/src/test/java/org/oppia/android/domain/exploration/ExplorationProgressControllerTest.kt
  scripts/assets/test_file_exemptions.textproto
  testing/src/main/java/org/oppia/android/testing/lightweightcheckpointing/ExplorationCheckpointTestHelper.kt
  testing/src/test/java/org/oppia/android/testing/lightweightcheckpointing/ExplorationCheckpointTestHelperTest.kt
Labels: PR: LGTM

#3471 Fix #3422: Separate MarkTopicsCompletedActivityTest into activity and fragment test files
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/oppia/android/app/activity/ActivityComponent.kt
  app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/testing/MarkTopicsCompletedTestActivity.kt
  app/src/main/res/layout/mark_topics_completed_fragment.xml
  app/src/main/res/layout/mark_topics_completed_topic_view.xml
  app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedActivityTest.kt
  app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt
  scripts/assets/test_file_exemptions.textproto
Labels: PR: LGTM

#3516 Fix #3418: Separate DeveloperOptionsActivityTest into activity and fragment test files
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/oppia/android/app/activity/ActivityComponent.kt
  app/src/main/java/org/oppia/android/app/devoptions/testing/DeveloperOptionsTestActivity.kt
  app/src/sharedTest/java/org/oppia/android/app/devoptions/DeveloperOptionsActivityTest.kt
  app/src/sharedTest/java/org/oppia/android/app/devoptions/DeveloperOptionsFragmentTest.kt
  scripts/assets/accessibility_label_exemptions.textproto
  scripts/assets/test_file_exemptions.textproto
Labels: PR: LGTM

#3601 Update oppiabot to version 1.4.0
  .github/workflows/oppiabot.yml
Labels: PR don't merge - NEEDS UPDATE
