Repository oppia/oppia-android, pull requests merged in 2022-11, with the labels that each got.

#4691 Localisation updates from https://translatewiki.net.
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-sw/strings.xml
Labels: PR: LGTM

#4468 Fixes #2627: Improve accessibility for Pin Verification Screen
  app/src/main/java/org/oppia/android/app/profile/PinPasswordActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/profile/PinPasswordViewModel.kt
  app/src/main/res/layout/pin_password_activity.xml
  app/src/main/res/values-sw600dp-land/dimens.xml
  app/src/main/res/values-sw600dp-port/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt
Labels: HACKTOBERFEST-ACCEPTED

#4656 Fix #3746: Add regex to ban <include> tag in layout files.
  app/src/main/res/layout-sw600dp/administrator_controls_activity.xml
  app/src/main/res/layout-sw600dp/help_activity.xml
  app/src/main/res/layout-sw600dp/option_activity.xml
  app/src/main/res/layout-sw600dp/options_without_drawer_activity.xml
  app/src/main/res/layout/add_profile_activity.xml
  app/src/main/res/layout/administrator_controls_activity.xml
  app/src/main/res/layout/developer_options_activity.xml
  app/src/main/res/layout/help_activity.xml
  app/src/main/res/layout/help_without_drawer_activity.xml
  app/src/main/res/layout/home_activity.xml
  app/src/main/res/layout/option_activity.xml
  app/src/main/res/layout/options_without_drawer_activity.xml
  app/src/main/res/layout/profile_progress_activity.xml
  app/src/main/res/layout/toolbar.xml
  scripts/assets/file_content_validation_checks.textproto
  scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt
Labels: PR: LGTM, HACKTOBERFEST-ACCEPTED

#4698 Localisation updates from https://translatewiki.net.
  app/src/main/res/values-ar/strings.xml
Labels: PR: LGTM

#4695 Fixes #4586: Improve text scaling according to screen reader
  app/src/main/res/layout-sw600dp-land/faq_single_activity.xml
  app/src/main/res/layout-sw600dp-land/resume_lesson_fragment.xml
  app/src/main/res/layout-sw600dp/help_activity.xml
  app/src/main/res/layout-sw600dp/option_activity.xml
  app/src/main/res/layout-sw600dp/story_fragment.xml
  app/src/main/res/layout/admin_auth_activity.xml
  app/src/main/res/layout/administrator_controls_activity.xml
  app/src/main/res/layout/app_language_activity.xml
  app/src/main/res/layout/app_version_activity.xml
  app/src/main/res/layout/audio_language_activity.xml
  app/src/main/res/layout/completed_story_list_fragment.xml
  app/src/main/res/layout/developer_options_activity.xml
  app/src/main/res/layout/exploration_activity.xml
  app/src/main/res/layout/faq_single_activity.xml
  app/src/main/res/layout/force_network_type_fragment.xml
  app/src/main/res/layout/help_activity.xml
  app/src/main/res/layout/hints_and_solution_fragment.xml
  app/src/main/res/layout/home_activity.xml
  app/src/main/res/layout/license_text_viewer_activity.xml
  app/src/main/res/layout/mark_chapters_completed_fragment.xml
  app/src/main/res/layout/mark_stories_completed_fragment.xml
  app/src/main/res/layout/mark_topics_completed_fragment.xml
  app/src/main/res/layout/math_expression_parser_fragment.xml
  app/src/main/res/layout/my_downloads_fragment.xml
  app/src/main/res/layout/ongoing_topic_list_fragment.xml
  app/src/main/res/layout/option_activity.xml
  app/src/main/res/layout/pin_password_activity.xml
  app/src/main/res/layout/profile_and_device_id_activity.xml
  app/src/main/res/layout/profile_edit_activity.xml
  app/src/main/res/layout/profile_list_fragment.xml
  app/src/main/res/layout/profile_picture_activity.xml
  app/src/main/res/layout/profile_progress_header.xml
  app/src/main/res/layout/profile_rename_activity.xml
  app/src/main/res/layout/profile_reset_pin_activity.xml
  app/src/main/res/layout/promoted_story_card.xml
  app/src/main/res/layout/reading_text_size_activity.xml
  app/src/main/res/layout/revision_card_activity.xml
  app/src/main/res/layout/story_fragment.xml
  app/src/main/res/layout/topic_fragment.xml
  app/src/main/res/layout/topic_practice_footer_view.xml
  app/src/main/res/layout/view_event_logs_fragment.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt
Labels: PR: LGTM

#4685 Fix #4641, #4674, #4579, #4591: Assorted beta fixes
  app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt
  app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt
  app/src/main/java/org/oppia/android/app/profile/AddProfileActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt
  app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditViewModel.kt
  app/src/main/res/layout-land/profile_edit_fragment.xml
  app/src/main/res/layout/add_profile_activity.xml
  app/src/main/res/layout/administrator_controls_download_permissions_view.xml
  app/src/main/res/layout/profile_edit_fragment.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-sw/strings.xml
  app/src/main/res/values/faqs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/terms_of_service.xml
  app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt
  app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt
  app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt
  app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt
  domain/BUILD.bazel
  domain/src/main/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasIntegerPartEqualToRuleClassifierProvider.kt
  domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterAlphaKenyaModule.kt
  domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterModule.kt
  domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt
  domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasIntegerPartEqualToRuleClassifierProviderTest.kt
  domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt
  scripts/assets/test_file_exemptions.textproto
  testing/src/main/java/org/oppia/android/testing/platformparameter/TestPlatformParameterModule.kt
  utility/src/main/java/org/oppia/android/util/caching/BUILD.bazel
  utility/src/main/java/org/oppia/android/util/caching/testing/BUILD.bazel
  utility/src/main/java/org/oppia/android/util/caching/testing/FakeAssetRepository.kt
  utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterConstants.kt
Labels: TODO: Review (post-merge), HACKTOBERFEST-ACCEPTED

#4705 Bump version codes for Beta MR2
  version.bzl
Labels: PR: LGTM

#4731 Fixes #4712: Ensure CoordinatorLayout Behaviors are not renamed/removed during binary optimizations
  config/proguard/androidx-proguard-rules.pro
Labels: PR: LGTM

#4733 Localisation updates from https://translatewiki.net.
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-sw/strings.xml
Labels: PR: LGTM

#4730 Fix #4709: Revert "Fix #2581: Marquee auto restart issue (#4392)"
  WORKSPACE
  app/BUILD.bazel
  app/build.gradle
  app/src/main/java/org/oppia/android/app/help/thirdparty/LicenseTextViewerActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt
  app/src/main/res/layout-sw600dp/story_fragment.xml
  app/src/main/res/layout/exploration_activity.xml
  app/src/main/res/layout/license_text_viewer_activity.xml
  app/src/main/res/layout/revision_card_activity.xml
  app/src/main/res/layout/story_fragment.xml
  app/src/main/res/layout/topic_fragment.xml
  app/src/main/res/values/styles.xml
  app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
  app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt
  app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt
  app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityTest.kt
  third_party/BUILD.bazel
Labels: PR: Cherrypick requested

#4745 Update version codes to prepare for RC02 of Beta MR2
  version.bzl
Labels: PR: Cherrypick requested, TODO: Review (post-merge)

#4747 Fix #4746: Update app to target SDK 31
  .github/actions/set-up-android-bazel-build-environment/action.yml
  BUILD.bazel
  WORKSPACE
  app/build.gradle
  app/src/main/AppAndroidManifest.xml
  app/src/main/DatabindingAdaptersManifest.xml
  app/src/main/DatabindingResourcesManifest.xml
  app/src/main/RecyclerviewAdaptersManifest.xml
  app/src/main/ViewModelManifest.xml
  app/src/main/ViewModelsManifest.xml
  app/src/main/ViewsManifest.xml
  build_flavors.bzl
  config/src/java/org/oppia/android/config/AndroidManifest.xml
  data/build.gradle
  data/src/test/AndroidManifest.xml
  domain/build.gradle
  domain/src/main/AndroidManifest.xml
  instrumentation/BUILD.bazel
  testing/build.gradle
  testing/src/test/AndroidManifest.xml
  utility/build.gradle
  utility/src/main/AndroidManifest.xml
Labels: PR: LGTM

#4568 Fix #4445: Add scaling animation for Continue button
  app/BUILD.bazel
  app/src/main/java/org/oppia/android/app/customview/ContinueButtonView.kt
  app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ContinueInteractionViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ContinueNavigationButtonViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/ImageRegionSelectionInteractionViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/MathExpressionInteractionsViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/NumericInputViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/RatioExpressionInputInteractionViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/SelectionInteractionViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/StateItemViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/TextInputViewModel.kt
  app/src/main/java/org/oppia/android/app/player/state/testing/StateFragmentTestActivity.kt
  app/src/main/java/org/oppia/android/app/profile/PinPasswordActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/splash/SplashActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/testing/InputInteractionViewTestActivity.kt
  app/src/main/java/org/oppia/android/app/utility/lifecycle/BUILD.bazel
  app/src/main/java/org/oppia/android/app/utility/lifecycle/LifecycleSafeTimerFactory.kt
  app/src/main/java/org/oppia/android/app/view/ViewComponentImpl.kt
  app/src/main/res/anim/scale_button_size.xml
  app/src/main/res/layout/continue_interaction_item.xml
  app/src/main/res/layout/continue_navigation_button_item.xml
  app/src/sharedTest/java/org/oppia/android/app/player/exploration/BUILD.bazel
  app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
  app/src/sharedTest/java/org/oppia/android/app/player/state/BUILD.bazel
  app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt
  app/src/test/java/org/oppia/android/app/player/state/StateFragmentLocalTest.kt
  domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt
  domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterAlphaKenyaModule.kt
  domain/src/main/java/org/oppia/android/domain/platformparameter/PlatformParameterModule.kt
  domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt
  domain/src/main/java/org/oppia/android/domain/question/QuestionAssessmentProgressController.kt
  domain/src/main/java/org/oppia/android/domain/state/StateDeck.kt
  domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt
  domain/src/test/java/org/oppia/android/domain/exploration/ExplorationProgressControllerTest.kt
  domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt
  domain/src/test/java/org/oppia/android/domain/question/QuestionAssessmentProgressControllerTest.kt
  model/src/main/proto/exploration.proto
  model/src/main/proto/profile.proto
  scripts/assets/test_file_exemptions.textproto
  testing/BUILD.bazel
  testing/src/main/java/org/oppia/android/testing/platformparameter/TestPlatformParameterModule.kt
  testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt
  utility/src/main/java/org/oppia/android/util/platformparameter/PlatformParameterConstants.kt
Labels: PR: LGTM

#4704 Fix #2546: Rename OngoingStory to PromotedStory
  app/BUILD.bazel
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingStoryClickListener.kt
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/PromotedStoryClickListener.kt
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/PromotedStoryListAdapter.kt
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/PromotedStoryViewModel.kt
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedFragment.kt
  app/src/main/java/org/oppia/android/app/home/recentlyplayed/RecentlyPlayedFragmentPresenter.kt
  app/src/main/res/layout/recently_played_story_card.xml
  scripts/assets/kdoc_validity_exemptions.textproto
  scripts/assets/test_file_exemptions.textproto
Labels: PR: LGTM

#4752 Fix #4750: Fixes SDK 31 support
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/oppia/android/app/application/AbstractOppiaApplication.kt
  app/src/main/java/org/oppia/android/app/application/ApplicationComponent.kt
  app/src/test/java/org/oppia/android/app/utility/datetime/DateTimeUtilTest.kt
  domain/BUILD.bazel
  domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/AnalyticsStartupListener.kt
  domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/BUILD.bazel
  domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader/BUILD.bazel
  domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader/LogReportWorkManagerInitializer.kt
  domain/src/main/java/org/oppia/android/domain/oppialogger/loguploader/LogReportWorkerModule.kt
  domain/src/main/java/org/oppia/android/domain/platformparameter/syncup/PlatformParameterSyncUpWorkManagerInitializer.kt
  domain/src/main/java/org/oppia/android/domain/platformparameter/syncup/PlatformParameterSyncUpWorkerModule.kt
  domain/src/test/java/org/oppia/android/domain/oppialogger/loguploader/LogReportWorkManagerInitializerTest.kt
  domain/src/test/java/org/oppia/android/domain/platformparameter/syncup/PlatformParameterSyncUpWorkManagerInitializerTest.kt
  scripts/assets/file_content_validation_checks.textproto
  scripts/assets/test_file_exemptions.textproto
  scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt
Labels: PR: Cherrypick requested, PR: LGTM

#4757 Fix #4756: Add support for logging an invested engagement event
  domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt
  domain/src/main/java/org/oppia/android/domain/oppialogger/analytics/LearnerAnalyticsLogger.kt
  domain/src/test/java/org/oppia/android/domain/exploration/ExplorationProgressControllerTest.kt
  domain/src/test/java/org/oppia/android/domain/oppialogger/analytics/LearnerAnalyticsLoggerTest.kt
  model/src/main/proto/oppia_logger.proto
  testing/src/main/java/org/oppia/android/testing/FakeAnalyticsEventLogger.kt
  testing/src/main/java/org/oppia/android/testing/logging/EventLogSubject.kt
  testing/src/test/java/org/oppia/android/testing/FakeAnalyticsEventLoggerTest.kt
  utility/src/main/java/org/oppia/android/util/logging/EventBundleCreator.kt
  utility/src/main/java/org/oppia/android/util/logging/KenyaAlphaEventTypeToHumanReadableNameConverterImpl.kt
  utility/src/main/java/org/oppia/android/util/logging/StandardEventTypeToHumanReadableNameConverterImpl.kt
  utility/src/test/java/org/oppia/android/util/logging/EventBundleCreatorTest.kt
Labels: PR: Cherrypick requested

#4763 Fix #4764: Spotlight overlays have some UI issues
  app/src/main/java/org/oppia/android/app/customview/ChapterNotStartedContainerConstraintLayout.kt
  app/src/main/java/org/oppia/android/app/customview/PromotedStoryCardView.kt
  app/src/main/java/org/oppia/android/app/onboarding/OnboardingActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragment.kt
  app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt
  app/src/main/java/org/oppia/android/app/player/exploration/ExplorationFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/spotlight/SpotlightFragment.kt
  app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt
  app/src/main/res/drawable/ic_close_black_24.xml
  app/src/main/res/drawable/spotlight_done_button_background.xml
  app/src/main/res/layout/bottom_left_overlay.xml
  app/src/main/res/layout/bottom_right_overlay.xml
  app/src/main/res/layout/onboarding_activity.xml
  app/src/main/res/layout/top_left_overlay.xml
  app/src/main/res/layout/top_right_overlay.xml
  app/src/main/res/values/strings.xml
  app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt
  app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt
  domain/src/main/java/org/oppia/android/domain/spotlight/SpotlightStateController.kt
  domain/src/test/java/org/oppia/android/domain/spotlight/SpotlightStateControllerTest.kt
  model/src/main/proto/spotlight.proto
Labels: PR: LGTM
