Repository oppia/oppia-android, pull requests merged in 2023-10, with the labels that each got.

#5165 Fix #4649: Updates audio option name
  app/src/main/res/values/strings.xml
Labels: Hacktoberfest

#5166 Fix #5164 Format strings.xml(values-en) so that string tags are on one line
  app/src/main/res/values/strings.xml
Labels: PR: LGTM

#5168 Fixes #2399: Reformatting required in dimension file for better structure
  app/src/main/res/values/dimens.xml
Labels: PR: LGTM

#5173 Fix #5171: Fixes all warnings in "Accessibility" category
  app/src/main/java/org/oppia/android/app/player/state/ImageRegionSelectionInteractionView.kt
  app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt
  app/src/main/res/layout-land/profile_chooser_fragment.xml
  app/src/main/res/layout-land/topic_info_fragment.xml
  app/src/main/res/layout-land/walkthrough_final_fragment.xml
  app/src/main/res/layout-land/walkthrough_welcome_fragment.xml
  app/src/main/res/layout-sw600dp-land/topic_info_fragment.xml
  app/src/main/res/layout-sw600dp-port/topic_info_fragment.xml
  app/src/main/res/layout-sw600dp/profile_chooser_fragment.xml
  app/src/main/res/layout-sw600dp/story_chapter_view.xml
  app/src/main/res/layout/activity_view_binding_adapters_test.xml
  app/src/main/res/layout/app_version_fragment.xml
  app/src/main/res/layout/bottom_left_overlay.xml
  app/src/main/res/layout/bottom_right_overlay.xml
  app/src/main/res/layout/continue_interaction_item.xml
  app/src/main/res/layout/continue_navigation_button_item.xml
  app/src/main/res/layout/drawer_fragment.xml
  app/src/main/res/layout/exploration_activity.xml
  app/src/main/res/layout/math_expression_parser_fragment.xml
  app/src/main/res/layout/next_button_item.xml
  app/src/main/res/layout/previous_button_item.xml
  app/src/main/res/layout/profile_chooser_fragment.xml
  app/src/main/res/layout/profile_picture_activity.xml
  app/src/main/res/layout/return_to_topic_button_item.xml
  app/src/main/res/layout/revision_card_activity.xml
  app/src/main/res/layout/story_chapter_view.xml
  app/src/main/res/layout/submit_button_item.xml
  app/src/main/res/layout/test_drawable_binding_adapter_activity.xml
  app/src/main/res/layout/test_image_view_bindable_adapter_activity.xml
  app/src/main/res/layout/test_url_parser_activity.xml
  app/src/main/res/layout/text_input_interaction_item.xml
  app/src/main/res/layout/top_left_overlay.xml
  app/src/main/res/layout/top_right_overlay.xml
  app/src/main/res/layout/topic_info_fragment.xml
  app/src/main/res/layout/walkthrough_final_fragment.xml
  app/src/main/res/layout/walkthrough_welcome_fragment.xml
  app/src/main/res/values/strings.xml
Labels: PR: LGTM

#5175 Fix #3691: Adds Resume Lesson Tablet Portrait UI
  app/src/main/res/layout-sw600dp-port/resume_lesson_fragment.xml
  app/src/main/res/values-sw600dp-port/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: PR: LGTM

#5183 Fixed #5182 - All warnings in "Internationalization"
  app/src/main/res/layout-land/profile_progress_header.xml
  app/src/main/res/layout-sw600dp/administrator_controls_learner_analytics_view.xml
  app/src/main/res/layout-sw600dp/profile_progress_header.xml
  app/src/main/res/layout/activity_input_interaction_view_test.xml
  app/src/main/res/layout/add_profile_activity.xml
  app/src/main/res/layout/administrator_controls_learner_analytics_view.xml
  app/src/main/res/layout/concept_card_fragment_test_activity.xml
  app/src/main/res/layout/exploration_test_activity.xml
  app/src/main/res/layout/font_scale_test_activity.xml
  app/src/main/res/layout/profile_progress_header.xml
  app/src/main/res/layout/spotlight_fragment_test_activity.xml
  app/src/main/res/layout/state_fragment_test_activity.xml
  app/src/main/res/values/strings.xml
Labels: PR: LGTM

#5190 Fix part of #5195: Changed method for compatibility with API < 26
  app/src/main/java/org/oppia/android/app/administratorcontrols/learneranalytics/ControlButtonsViewModel.kt
Labels: Hacktoberfest, PR: LGTM

#5152 Fix #4739 Talkback does not read the expected text
  app/src/main/java/org/oppia/android/app/profile/PinPasswordActivityPresenter.kt
  app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt
Labels: PR: LGTM

#5198 Fix part of #5195: RestrictedApi. Using a private API
  app/src/main/java/org/oppia/android/app/databinding/AppCompatCheckBoxBindingAdapters.java
  app/src/sharedTest/java/org/oppia/android/app/databinding/AppCompatCheckBoxBindingAdaptersTest.kt
Labels: Hacktoberfest, PR: LGTM

#5096 Fix part of #5025: App and OS Deprecation Milestone 3 - Add New Deprecation Dialog Fragments
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/oppia/android/app/fragment/FragmentComponentImpl.kt
  app/src/main/java/org/oppia/android/app/notice/DeprecationNoticeActionListener.kt
  app/src/main/java/org/oppia/android/app/notice/ForcedAppDeprecationNoticeDialogFragment.kt
  app/src/main/java/org/oppia/android/app/notice/ForcedAppDeprecationNoticeDialogFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/notice/OptionalAppDeprecationNoticeDialogFragment.kt
  app/src/main/java/org/oppia/android/app/notice/OptionalAppDeprecationNoticeDialogFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/notice/OsDeprecationNoticeDialogFragment.kt
  app/src/main/java/org/oppia/android/app/notice/OsDeprecationNoticeDialogFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/notice/testing/BUILD.bazel
  app/src/main/java/org/oppia/android/app/notice/testing/ForcedAppDeprecationNoticeDialogFragmentTestActivity.kt
  app/src/main/java/org/oppia/android/app/notice/testing/OptionalAppDeprecationNoticeDialogFragmentTestActivity.kt
  app/src/main/java/org/oppia/android/app/notice/testing/OsDeprecationNoticeDialogFragmentTestActivity.kt
  app/src/main/java/org/oppia/android/app/splash/SplashActivity.kt
  app/src/main/java/org/oppia/android/app/splash/SplashActivityPresenter.kt
  app/src/main/res/values/strings.xml
  app/src/sharedTest/java/org/oppia/android/app/notice/BUILD.bazel
  app/src/sharedTest/java/org/oppia/android/app/notice/ForcedAppDeprecationNoticeDialogFragmentTest.kt
  app/src/sharedTest/java/org/oppia/android/app/notice/OptionalAppDeprecationNoticeDialogFragmentTest.kt
  app/src/sharedTest/java/org/oppia/android/app/notice/OsDeprecationNoticeDialogFragmentTest.kt
  scripts/assets/test_file_exemptions.textproto
Labels: PR: LGTM

#5209 Localisation updates from https://translatewiki.net.
  app/src/main/res/values-pcm-rNG/strings.xml
Labels: PR: LGTM

#5205 Fixes #4708: Don't submit answer if it's invalid according to the input
  app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt
  app/src/main/java/org/oppia/android/app/player/state/StateViewModel.kt
  app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt
Labels: Hacktoberfest

#5207 Fix part of #5195: using viewLifecycleOwner
  app/src/main/java/org/oppia/android/app/survey/SurveyFragmentPresenter.kt
Labels: PR: LGTM

#5212 Fix #5032 Images in Arabic (RTL) lessons are right-aligned rather than center-aligned.
  utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt
  utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt
Labels: PR: LGTM

#5219 fix: Fix Translate Wiki Issues with Splash Activity Screen Strings
  app/src/main/res/values/strings.xml
Labels: PR: LGTM

#5210 Fix #5214, Fix Part of #1723 : Fix onboarding issue faced by new contributors
  wiki/Installing-Oppia-Android.md
  wiki/Oppia-Android-Testing.md
Labels: PR: LGTM
